building_name: jtc
levels:
  L1_JTC:
    lanes:
    - - 0
      - 1
      - {door_name: '', speed_limit: 0}
    - - 1
      - 0
      - {door_name: '', speed_limit: 0}
    - - 2
      - 3
      - {speed_limit: 0}
    - - 3
      - 2
      - {speed_limit: 0}
    - - 3
      - 4
      - {speed_limit: 0}
    - - 4
      - 3
      - {speed_limit: 0}
    - - 4
      - 5
      - {door_name: '', speed_limit: 0}
    - - 5
      - 4
      - {door_name: '', speed_limit: 0}
    - - 2
      - 6
      - {speed_limit: 0}
    - - 6
      - 2
      - {speed_limit: 0}
    - - 6
      - 7
      - {speed_limit: 0}
    - - 7
      - 6
      - {speed_limit: 0}
    - - 8
      - 9
      - {speed_limit: 0}
    - - 9
      - 8
      - {speed_limit: 0}
    - - 6
      - 9
      - {speed_limit: 0}
    - - 9
      - 6
      - {speed_limit: 0}
    - - 9
      - 10
      - {speed_limit: 0}
    - - 10
      - 9
      - {speed_limit: 0}
    - - 11
      - 12
      - {speed_limit: 0}
    - - 12
      - 11
      - {speed_limit: 0}
    - - 1
      - 13
      - {speed_limit: 0}
    - - 13
      - 1
      - {speed_limit: 0}
    - - 13
      - 14
      - {speed_limit: 0}
    - - 14
      - 13
      - {speed_limit: 0}
    - - 10
      - 14
      - {speed_limit: 0}
    - - 14
      - 10
      - {speed_limit: 0}
    - - 15
      - 16
      - {speed_limit: 0}
    - - 16
      - 15
      - {speed_limit: 0}
    - - 16
      - 17
      - {speed_limit: 0}
    - - 17
      - 16
      - {speed_limit: 0}
    - - 17
      - 18
      - {speed_limit: 0}
    - - 18
      - 17
      - {speed_limit: 0}
    - - 18
      - 5
      - {speed_limit: 0}
    - - 5
      - 18
      - {speed_limit: 0}
    - - 18
      - 19
      - {speed_limit: 0}
    - - 19
      - 18
      - {speed_limit: 0}
    - - 11
      - 19
      - {speed_limit: 0}
    - - 19
      - 11
      - {speed_limit: 0}
    - - 20
      - 21
      - {speed_limit: 0}
    - - 21
      - 20
      - {speed_limit: 0}
    - - 21
      - 0
      - {speed_limit: 0}
    - - 0
      - 21
      - {speed_limit: 0}
    - - 10
      - 22
      - {speed_limit: 0}
    - - 22
      - 10
      - {speed_limit: 0}
    - - 22
      - 23
      - {speed_limit: 0}
    - - 23
      - 22
      - {speed_limit: 0}
    vertices:
    - - 51.834867503104775
      - -58.37306686496059
      - {name: l1door_inside}
    - - 50.13675815755668
      - -61.254692030802666
      - {name: l1door_outside}
    - - 68.27538986847566
      - -81.17591815868731
      - {name: turnstile2}
    - - 79.1613232127294
      - -81.192965935624
      - {name: turnstile1}
    - - 79.15943867956463
      - -82.95874451819633
      - {name: turnstile1_outside}
    - - 79.153176230894
      - -84.90564123431209
      - {name: turnstile1_inside}
    - - 58.84567878986719
      - -81.18047003110068
      - {name: ''}
    - - 58.87293203871157
      - -75.19983155065573
      - {name: ''}
    - - 57.57619926444174
      - -75.21319723971665
      - {name: ''}
    - - 57.55773083942699
      - -81.20685349540747
      - {name: ''}
    - - 53.75523579082414
      - -81.12689130358535
      - {name: ''}
    - - 80.11512893664678
      - -93.45457949734252
      - {name: ''}
    - - 77.01336130434157
      - -93.46246554381663
      - {name: ''}
    - - 49.13873838631198
      - -62.62840073664891
      - {name: tl_corner}
    - - 49.503786956737045
      - -81.2980938934003
      - {name: bl_corner}
    - - 66.51364128759415
      - -93.5181607470401
      - {lift: l22_lift, name: ''}
    - - 69.83479757309662
      - -93.57234832373173
      - {name: ''}
    - - 69.98631403954418
      - -85.68276472582772
      - {name: ''}
    - - 79.1058599520493
      - -85.71999150403643
      - {name: ''}
    - - 80.15261665021677
      - -86.82134167834641
      - {name: ''}
    - - 45.89563076664894
      - -51.11433799216809
      - {lift: kitchen_lift, lift_cabin: kitchen_lift, name: ''}
    - - 48.06707685755162
      - -52.61445538414357
      - {name: ''}
    - - 50.8750022802422
      - -88.98614841394551
      - {name: ''}
    - - 51.69767348870945
      - -92.44136748950797
      - {name: L1_home_base}
  L22_JTC:
    lanes:
    - - 0
      - 1
      - {is_bidirectional: false, speed_limit: 0}
    - - 1
      - 2
      - {is_bidirectional: false, speed_limit: 0}
    - - 2
      - 3
      - {is_bidirectional: false, speed_limit: 0}
    - - 3
      - 4
      - {is_bidirectional: false, speed_limit: 0}
    vertices:
    - - 66.48590012386238
      - -93.63028236588195
      - {lift: l22_lift, name: ''}
    - - 68.9175933805915
      - -93.64051386034764
      - {name: ''}
    - - 69.87657436446061
      - -93.64378018464141
      - {name: ''}
    - - 69.85317890281674
      - -97.63147571929015
      - {name: ''}
    - - 69.85550930202953
      - -100.70660507272324
      - {name: ''}
  L2_JTC:
    lanes:
    - - 0
      - 1
      - {speed_limit: 0}
    - - 1
      - 0
      - {speed_limit: 0}
    - - 1
      - 2
      - {speed_limit: 0}
    - - 2
      - 1
      - {speed_limit: 0}
    - - 2
      - 3
      - {speed_limit: 0}
    - - 3
      - 2
      - {speed_limit: 0}
    - - 3
      - 4
      - {speed_limit: 0}
    - - 4
      - 3
      - {speed_limit: 0}
    - - 4
      - 5
      - {speed_limit: 0}
    - - 5
      - 4
      - {speed_limit: 0}
    - - 5
      - 6
      - {speed_limit: 0}
    - - 6
      - 5
      - {speed_limit: 0}
    - - 2
      - 7
      - {speed_limit: 0}
    - - 7
      - 2
      - {speed_limit: 0}
    - - 0
      - 8
      - {speed_limit: 0}
    - - 8
      - 0
      - {speed_limit: 0}
    - - 9
      - 8
      - {speed_limit: 0}
    - - 8
      - 9
      - {speed_limit: 0}
    - - 9
      - 10
      - {speed_limit: 0}
    - - 10
      - 9
      - {speed_limit: 0}
    - - 6
      - 11
      - {speed_limit: 0}
    - - 11
      - 6
      - {speed_limit: 0}
    - - 11
      - 12
      - {speed_limit: 0}
    - - 12
      - 11
      - {speed_limit: 0}
    - - 1
      - 13
      - {speed_limit: 0}
    - - 13
      - 1
      - {speed_limit: 0}
    vertices:
    - - 53.36247062376679
      - -59.09143898890406
      - {name: point_1}
    - - 62.43725486265532
      - -52.03453859124046
      - {name: point_2}
    - - 75.55768981906397
      - -51.40212196945731
      - {name: point_3}
    - - 89.03982554499125
      - -59.48672595754473
      - {name: point_4}
    - - 90.79464972499657
      - -68.92233859872208
      - {name: point_5}
    - - 89.67203555367797
      - -71.7983590575125
      - {name: point_6}
    - - 86.70666013608935
      - -72.74272846890125
      - {name: point_7}
    - - 80.37657972805988
      - -52.50189226508897
      - {name: kitchen}
    - - 49.56621302920713
      - -56.430092818549014
      - {name: door_inside}
    - - 48.996895070940795
      - -52.9461930172082
      - {name: lift_outside}
    - - 46.02594023790364
      - -51.56543227584035
      - {lift: kitchen_lift, name: lift_inside}
    - - 86.63931464884129
      - -84.3788382206055
      - {name: point_8}
    - - 86.66338131911402
      - -86.00252277471304
      - {is_charger: true, name: charging_point}
    - - 54.37518727253429
      - -52.41323126405203
      - {name: L2_home_base}
  L6_JTC:
    lanes:
    - - 0
      - 1
      - {speed_limit: 0}
    - - 1
      - 0
      - {speed_limit: 0}
    - - 0
      - 2
      - {speed_limit: 0}
    - - 2
      - 0
      - {speed_limit: 0}
    vertices:
    - - 80.32272919266326
      - -93.63032240961422
      - {name: lift2_outside}
    - - 76.91352310425751
      - -93.6256195960301
      - {name: lift2_inside}
    - - 81.70922304856198
      - -93.62726227950118
      - {is_charger: true, name: waiting_point}
